run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/getlawrence/vercelreceiver)
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/getlawrence/vercelreceiver
  govet:
    settings:
      printf:
        funcs:
          - (github.com/getlawrence/vercelreceiver/vendor/github.com/go-logr/logr.Logger).Info
          - (github.com/getlawrence/vercelreceiver/vendor/github.com/go-logr/logr.Logger).Error
          - (github.com/getlawrence/vercelreceiver/vendor/github.com/go-logr/logr.Logger).V
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  unparam:
    check-exported: false
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - goconst
        - dupl
        - gocyclo
    - path: testdata/
      linters:
        - gosec
        - goconst
        - dupl
        - gocyclo
        - funlen
        - gomnd
    - path: factory_test\.go
      linters:
        - gocyclo
    - path: integration_test\.go
      linters:
        - gocyclo
        - funlen
        - gomnd
