run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/getlawrence/vercelreceiver)
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/getlawrence/vercelreceiver
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 200
  unparam:
    check-exported: false
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - rangeValCopy
      - stringXbytes
      - hugeParam
      - httpNoBody
      - paramTypeCombine
  funlen:
    lines: 100
    statements: 50
  gosec:
    excludes:
      - G112 # Slowloris Attack - acceptable for internal collector

linters:
  disable-all: true
  enable:
    - bodyclose
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - goconst
        - dupl
        - gocyclo
        - lll
        - noctx
    - path: testdata/
      linters:
        - gosec
        - goconst
        - dupl
        - gocyclo
        - funlen
        - gomnd
    - path: factory_test\.go
      linters:
        - gocyclo
    - path: integration_test\.go
      linters:
        - gocyclo
        - funlen
        - gomnd
        - noctx
